apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  labels:
   {{- include "spring.labels" . | nindent 4 }}
spec:
  {{ if eq .Values.loadblancer "enabled" }}type: LoadBalancer{{ end }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
{{- include "spring.labels" . | nindent 4 }}

