apiVersion: apps/v1
kind: Deployment
metadata:
  name: animals-deployment
spec:
  selector:
    matchLabels:
      app: animals
  replicas: 2 
  template: 
    metadata:
      labels:
        app: animals
    spec:
      containers:
      - name: bear
        image: supergiantkir/animals:bear
        ports:
        - containerPort: 80
---
kind: Service      
apiVersion: v1     
metadata:
  name: animals-svc
spec:
  type: LoadBalancer
  selector:
    app: animals    
  ports:          
  - name: http    
    protocol: TCP
    port: 80
    targetPort: 80
    

