apiVersion: v1 # K8S API Version
kind: Pod  # Object Type
metadata: 
 name: nginx 
spec:
 containers: # NOTE THAT BELOW HERE WE CAN ADD AS MANY CONTAINERS WE WISH TO ENCAPSULATE IN THE SAME POD
 - name: nginx 
   image: nginx:1.7.9 
   ports: 
   - containerPort: 80
 - name: springapp
   image: yanivomc/spring-music:latest
   ports: 
   - containerPort: 8080
